# Generated by Django 6.0.2 on 2026-02-09 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isim", models.CharField(max_length=200)),
                ("konu", models.TextField()),
                ("fragman_url", models.URLField(blank=True, null=True)),
                (
                    "poster_url",
                    models.URLField(
                        blank=True, default="https://via.placeholder.com/300x450"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Yorum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kullanici_adi", models.CharField(default="Misafir", max_length=50)),
                ("icerik", models.TextField()),
                ("tarih", models.DateTimeField(auto_now_add=True)),
                ("ai_karari", models.CharField(blank=True, max_length=20)),
                ("ai_guveni", models.FloatField(default=0.0)),
                (
                    "film",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yorumlar",
                        to="filmler.film",
                    ),
                ),
            ],
        ),
    ]
