# Generated by Django 6.0.2 on 2026-02-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("filmler", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="film",
            name="oyuncular",
            field=models.CharField(default="Bilgi Yok", max_length=300),
        ),
        migrations.AddField(
            model_name="film",
            name="puan",
            field=models.FloatField(default=7.5),
        ),
        migrations.AddField(
            model_name="film",
            name="yil",
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name="film",
            name="poster_url",
            field=models.URLField(default="https://via.placeholder.com/300x450"),
        ),
    ]
