# Generated by Django 6.0.2 on 2026-02-12 14:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("filmler", "0002_film_oyuncular_film_puan_film_yil_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="film",
            name="eklenme_tarihi",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="film",
            name="turler",
            field=models.CharField(
                blank=True, default="", max_length=250, verbose_name="Kategoriler"
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="fragman_url",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Fragman URL"
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="isim",
            field=models.CharField(max_length=200, verbose_name="Film Adı"),
        ),
        migrations.AlterField(
            model_name="film",
            name="konu",
            field=models.TextField(blank=True, null=True, verbose_name="Özet / Konu"),
        ),
        migrations.AlterField(
            model_name="film",
            name="oyuncular",
            field=models.CharField(
                blank=True,
                default="Bilgi Yok",
                max_length=500,
                verbose_name="Oyuncular",
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="poster_url",
            field=models.CharField(
                blank=True,
                default="https://via.placeholder.com/300x450",
                max_length=500,
                null=True,
                verbose_name="Poster URL",
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="puan",
            field=models.FloatField(default=0.0, verbose_name="IMDb Puanı"),
        ),
        migrations.AlterField(
            model_name="film",
            name="yil",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Yapım Yılı"
            ),
        ),
        migrations.AlterField(
            model_name="yorum",
            name="ai_guveni",
            field=models.FloatField(default=0.0, verbose_name="Güven Skoru"),
        ),
        migrations.AlterField(
            model_name="yorum",
            name="ai_karari",
            field=models.CharField(blank=True, max_length=20, verbose_name="AI Kararı"),
        ),
        migrations.AlterField(
            model_name="yorum",
            name="icerik",
            field=models.TextField(verbose_name="Yorum İçeriği"),
        ),
    ]
