# Generated by Django 6.0.2 on 2026-02-12 18:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("filmler", "0003_film_eklenme_tarihi_film_turler_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="film",
            options={
                "ordering": ["-eklenme_tarihi"],
                "verbose_name": "Film",
                "verbose_name_plural": "Filmler",
            },
        ),
        migrations.AlterModelOptions(
            name="yorum",
            options={
                "ordering": ["-tarih"],
                "verbose_name": "Yorum",
                "verbose_name_plural": "Yorumlar",
            },
        ),
    ]
