# Generated by Django 6.0.2 on 2026-02-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("filmler", "0004_alter_film_options_alter_yorum_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="yorum",
            name="ai_kaynak",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="AI Kaynak Model"
            ),
        ),
    ]
